export const ACTIONS = Object.freeze({
  GO_TO_SETTINGS: "go_to_settings",
  TEAM_A: "team_a",
  TEAM_B: "team_b",
  EVENT_SWIPE_UP: "event_swipe_up",
  EVENT_SWIPE_DOWN: "event_swipe_down",
  EVENT_ONE_TAP: "event_one_tap",
  EVENT_TWO_TAPS: "event_two_tap",
  EVENT_THREE_TAPS: "event_three_tap",
  PAGE_FLIPPED: "page_flipped",
  OPEN_MODAL_SETTING: "open_modal_Setting",
  RESET_GAME: "reset_game",
  SWITCH_SCORES: "switch_scores",
  NEW_SET: "new_set",
  CHECK_WINNER: "check_winner",
  TOUCH_START: "touch_start",
  PAGE_REFRESH: "page_refresh",
  TEAMNAME_VISIBILITY_CHANGED: "TEAMNAME_VISIBILITY_CHANGED",
});
